// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZjTrdyyOPTdVIwpcGJWAWinhB-2ZmKv0',
    appId: '1:1018667371237:web:b414740f90c289e3d3620c',
    messagingSenderId: '1018667371237',
    projectId: 'qubico-80f2c',
    authDomain: 'qubico-80f2c.firebaseapp.com',
    storageBucket: 'qubico-80f2c.firebasestorage.app',
    measurementId: 'G-Y8M93L6H4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcmFd8zqgXx3xeJKfBLtbX8Ryt9_JHrA8',
    appId: '1:1018667371237:android:5cd1d4b84c3f51d3d3620c',
    messagingSenderId: '1018667371237',
    projectId: 'qubico-80f2c',
    storageBucket: 'qubico-80f2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuxOUfdoqoByX3p9D_bp4ENL8Kxh7XFvU',
    appId: '1:1018667371237:ios:32a8c30c7b4a9a75d3620c',
    messagingSenderId: '1018667371237',
    projectId: 'qubico-80f2c',
    storageBucket: 'qubico-80f2c.firebasestorage.app',
    iosBundleId: 'com.example.qubico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuxOUfdoqoByX3p9D_bp4ENL8Kxh7XFvU',
    appId: '1:1018667371237:ios:32a8c30c7b4a9a75d3620c',
    messagingSenderId: '1018667371237',
    projectId: 'qubico-80f2c',
    storageBucket: 'qubico-80f2c.firebasestorage.app',
    iosBundleId: 'com.example.qubico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZjTrdyyOPTdVIwpcGJWAWinhB-2ZmKv0',
    appId: '1:1018667371237:web:4b7ffe574706dc4dd3620c',
    messagingSenderId: '1018667371237',
    projectId: 'qubico-80f2c',
    authDomain: 'qubico-80f2c.firebaseapp.com',
    storageBucket: 'qubico-80f2c.firebasestorage.app',
    measurementId: 'G-TJBBV4P1BC',
  );
}
